__author__ = 'Jianfeng'

"""Bucket sort runs in linear expected time when the input is drawn
from a uniform distribution.
Bucket sort assumes that the input is generated by a random process
that distributes elements uniformly over the interval [0, 1).
"""
from insertion import insertion_sort

def bucket_sort(a):
    n = len(a)
    b = [[] for x in range(n)]
    for x in a:
        b[int(n * x)].append(x)
    c = []
    for i in range(n):
        insertion_sort(b[i])
        c += b[i]
    return c

def main():
    import random
    n = 20
    a = [random.random() for x in range(n)]
    print "Unsorted: ", a
    a = bucket_sort(a)
    print "Sorted: ", a

if __name__ == '__main__':
    main()

